### ISSUE TITLE
commande dependency finder xml issue

### ISSUE THREAD

**Issue by pushinwork** [v-m/GDGNC#1]
je suis windows, avec le programme anaconda et lorsque je lance la commande: xmldepgraph.py <folder> <xmlfile> <pathtodepfindbin>;
j'ai l'erreur ci dessous stipulant que le fichier "test.xml" spécifié en entrée n'est pas un fichier de commande ...,
![capture](https://cloud.githubusercontent.com/assets/6019219/12705140/b8e45f10-c86b-11e5-9eed-4476c8621ef3.PNG)

**Comment by pushinwork** [comment]
j'utilise python 3.5, et j'ai du faire quelques modif ds le code, pour le faire fonctionner

**Comment by pushinwork** [comment]
environnement windows, python 3.5, en respectant les arguments à fournir en entrée "xmldepgraph.py <folder> <xmlfile> <pathtodepfindbin>"

**Comment by monperrus** [comment]
pour ce projet, il faut utiliser python2
